shared/panels/contribution-sidepanel/_features/kpi/kpi.tsx, shared/panels/contribution-sidepanel/_features/kpi/kpi.types.ts, shared/panels/contribution-sidepanel/contributions-sidepanel.en.json, shared/panels/contribution-sidepanel/contributions-sidepanel.tsx
e-2083-component-kpi-component
=> KPI component

app/manage-projects/[projectSlug]/features/issues/_features/list-view/list-view.tsx, core/domain/application/application-contract.types.ts, core/domain/application/models/application-list-item-model.ts, shared/features/card-contribution-kanban/card-contribution-kanban.tsx, shared/features/card-contribution-kanban/card-contribution-kanban.types.ts, shared/panels/contribution-sidepanel/_features/application-card/application-card.tsx, shared/panels/contribution-sidepanel/_features/application-card/application-card.types.ts, shared/panels/contribution-sidepanel/_features/applications-accordion/applications-accordion.tsx, shared/panels/contribution-sidepanel/_features/applications-accordion/applications-accordion.types.ts, shared/panels/contribution-sidepanel/contributions-sidepanel.en.json, shared/panels/contribution-sidepanel/contributions-sidepanel.tsx
e-2084-component-devs-selection-component
=> Devs selection component

core/domain/contribution/models/contribution-activity-model.ts, shared/panels/contribution-sidepanel/_features/application-card/application-card.tsx, shared/panels/contribution-sidepanel/_features/applications-accordion/applications-accordion.tsx, shared/panels/contribution-sidepanel/_features/header/header.tsx, shared/panels/contribution-sidepanel/_features/header/header.types.ts, shared/panels/contribution-sidepanel/_features/helper/helper.tsx, shared/panels/contribution-sidepanel/_features/helper/helper.types.ts, shared/panels/contribution-sidepanel/contributions-sidepanel.en.json, shared/panels/contribution-sidepanel/contributions-sidepanel.hooks.tsx, shared/panels/contribution-sidepanel/contributions-sidepanel.tsx
=> Helper text component && E-2089

core/application/react-query-adapter/application/client/index.ts, core/application/react-query-adapter/application/client/use-patch-application.ts, core/domain/application/application-contract.types.ts, core/domain/application/input/application-facade-port.ts, core/domain/application/outputs/application-storage-port.ts, core/infrastructure/marketplace-api-client-adapter/adapters/application-client-adapter.ts, core/infrastructure/marketplace-api-client-adapter/adapters/contribution-client-adapter.ts, core/infrastructure/marketplace-api-client-adapter/mock-adapters/application-client-adapter-mock.ts, shared/panels/contribution-sidepanel/_features/application-card/application-card.tsx, shared/panels/contribution-sidepanel/_features/application-card/application-card.types.ts, shared/panels/contribution-sidepanel/_features/applications-accordion/applications-accordion.tsx, shared/panels/contribution-sidepanel/_features/applications-accordion/applications-accordion.types.ts, shared/panels/contribution-sidepanel/_features/assign-contributors/assign-contributors.tsx, shared/panels/contribution-sidepanel/_features/assign-contributors/assign-contributors.types.ts, shared/panels/contribution-sidepanel/_features/assigne-contributors/assigne-contributors.tsx, shared/panels/contribution-sidepanel/_features/assigne-contributors/assigne-contributors.types.ts, shared/panels/contribution-sidepanel/contributions-sidepanel.hooks.tsx
e-2105-assign-and-reject-contributors-request
=> Add assign and reject patch

app/globals.css, shared/theme/colors.ts
e-2165-designsystem-colors-branding-modifications
=> DS : colors branding

app/globals.css
e-2167-designsystemcolors-gradients-base
=> DS : color gradient

app/globals.css, design-system/molecules/toaster/adapters/sonner/sonner.adapter.tsx, design-system/molecules/toaster/adapters/sonner/sonner.variants.ts, design-system/molecules/toaster/toaster.stories.tsx, shared/theme/colors.ts
=> DS : toaster

shared/panels/_flows/reward-flow/_panels/bulk-contributor-selection/bulk-contributor-selection.tsx
b-2645-bulk-contributors-selection-when-only-1-contributor-is
=> QA : Open single panel if 1 contributor

shared/panels/_flows/reward-flow/_panels/_components/user-contributions/user-contributions.tsx
e-2204-qa-nb-de-contributions-ne-match-pas-22-4
=> QA : contributions number

shared/panels/_flows/reward-flow/_panels/_components/user-contributions/user-contributions.tsx, shared/panels/_flows/reward-flow/reward-flow.context.tsx, shared/panels/_flows/reward-flow/reward-flow.types.ts, shared/translation/translations/common/common.en.json
e-2212-snack-select-all-unselect
=> QA : unselect and select all && E-2205

shared/features/kanban/kanban-column/kanban-column.tsx
e-2210-qa-contributions-kanban-full-width
=> QA : kanban width

app/manage-projects/[projectSlug]/_translations/manage-project-detail.en.json, app/manage-projects/[projectSlug]/features/rewards-table/_components/filter-columns/filter-columns.hooks.tsx, design-system/atoms/button/adapters/default/default.adapter.tsx, shared/components/mutation/_translations/mutation.en.json, shared/components/mutation/_translations/mutation.translate.ts, shared/components/mutation/reward/cancel-reward.tsx, shared/components/mutation/reward/cancel-reward.types.ts, shared/translation/en.ts
e-2207-qa-le-toaster-de-schrodinger-elle-est-cancel-ou-pas
=> QA : toaster reward

shared/hooks/contributions/use-contribution-actions.tsx
e-2227-qa-should-be-able-to-click-on-an-other-contribution-if-panel
=> QA : open new contributor

shared/panels/contribution-sidepanel/_features/assign-contributors/assign-contributors.tsx
=> QA : KPI update

shared/modals/manage-applicants-modal/_components/applicants-table/_components/filter-columns/filter-columns.hooks.tsx, shared/modals/manage-applicants-modal/_translations/manage-applicants.en.json
e-2245-cta-should-be-ignore-not-reject
=> QA : change cta to ignore

app/manage-projects/[projectSlug]/features/rewards-table/_components/filter-columns/filter-columns.hooks.tsx
e-2248-i-should-be-able-to-cancel-a-reward-in-pending-request
=> QA : cancel a reward in pending request

shared/features/filters/contributor-project-filter/contributor-project-filter.en.json
=> QA : wording

shared/features/navigation/menu/primary-menu/primary-menu.tsx, shared/hooks/programs/use-show-programs-list.ts, shared/hooks/projects/use-show-projects-list.ts, shared/hooks/sponsors/use-show-sponsor-list.ts
e-2266-snack-debloquer-le-menu-new-app-pour-acceder-aux-projets
=> e-2266-snack-debloquer-le-menu-new-app-pour-acceder-aux-projets

design-system/molecules/cards/card-notification/adapters/default/default.adapter.tsx, design-system/molecules/cards/card-notification/card-notification.stories.tsx, design-system/molecules/cards/card-notification/card-notification.types.ts, shared/features/notifications/_components/notifications-content/notifications-content.tsx
e-2304-sub-notification-if-read-enlever-la-pastille-verte
=> Notifications : pastille verte

shared/panels/contributor-sidepanel/_components/kpi/kpi.tsx
=> KPI alignment

app/data/deep-dive/_features/contributors-table/_components/filter-columns/filter-columns.hooks.tsx, app/data/deep-dive/_features/contributors-table/_components/filter-columns/filter-columns.tsx, app/manage-projects/[projectSlug]/features/contributors-table/_components/filter-columns/filter-columns.hooks.tsx, app/manage-projects/[projectSlug]/features/contributors-table/_components/filter-columns/filter-columns.tsx, shared/modals/manage-applicants-modal/_components/applicants-table/_components/filter-columns/filter-columns.hooks.tsx, shared/modals/manage-rewards-modal/_components/contributors-table/_components/filter-columns/filter-columns.hooks.tsx
=> Tooltips country

app/globals.css, shared/features/app-wrapper/app-wrapper.tsx, shared/panels/contribution-sidepanel/_features/rewarded-card/rewarded-card.tsx
e-2124-designsystem-background-for-global-app
=> DS : background global app

design-system/molecules/alert/adapters/default/default.adapter.tsx, design-system/molecules/alert/alert.stories.tsx, design-system/molecules/alert/alert.types.ts, shared/panels/contribution-sidepanel/_features/helper/helper.tsx
e-2168-designsystem-add-default-icon-to-alert-but-custom-possible
=> DS : default icon

design-system/molecules/item-nav/adapters/default/default.adapter.tsx
e-2349-parent-improvement-admin-app
=> QA : improve hover

shared/features/filters/accordion-filter/accordion-filter.tsx
e-2359-filter-filtre-actif-pas-assez-visible
=> QA : filters brand

app/data/deep-dive/_features/contributors-table/_components/filter-columns/filter-columns.hooks.tsx, app/data/deep-dive/_features/projects-table/_components/filter-columns/filter-columns.hooks.tsx, app/financials/[sponsorId]/_features/programs-table/programs-table.tsx, app/manage-projects/[projectSlug]/features/contributors-table/_components/filter-columns/filter-columns.hooks.tsx, app/manage-projects/[projectSlug]/features/rewards-table/_components/filter-columns/filter-columns.hooks.tsx, app/manage-projects/features/projects-table/components/filter-columns/filter-columns.hooks.tsx, app/programs/[programId]/_features/projects-table/projects-table.tsx, app/programs/_features/programs-table/programs-table.tsx, core/kernel/money/money-adapter-mock.ts, core/kernel/money/money-adapter.ts, design-system/atoms/table-header/adapters/react-table/react-table.variants.ts, shared/modals/manage-applicants-modal/_components/applicants-table/_components/filter-columns/filter-columns.hooks.tsx, shared/panels/_flows/reward-flow/modals/manage-rewards-modal/_components/filter-columns/filter-columns.hooks.tsx
p-862-table-remplacer-les-na-en
=> QA : change N/A

app/manage-projects/[projectSlug]/_sections/financial-section/financial-section.tsx, app/manage-projects/[projectSlug]/_translations/manage-project-detail.en.json, shared/panels/project-update-sidepanel/project-update-sidepanel.en.json
e-2402-wording-edit-project-plutot-que-modify
=> QA : edit project

shared/modals/manage-applicants-modal/_components/applicants-table/_components/accordion-ignored-contributors/accordion-ignored-contributors.tsx, shared/modals/manage-applicants-modal/_components/applicants-table/_components/accordion-new-contributors/accordion-new-contributors.tsx, shared/modals/manage-applicants-modal/_components/applicants-table/_components/accordion-project-contributors/accordion-project-contributors.tsx
e-2401-manage-in-full-page-applicants-ouvrir-les-sections-par
=> QA : manage full page accordion

shared/features/card-contribution-kanban/card-contribution-kanban-translate.en.json, shared/hooks/contributions/use-contribution-actions.tsx
e-2400-card-kanban-message-derreur-insufficient-permissions
=> QA : kanban tooltip

design-system/molecules/cards/card-contribution-kanban/adapters/next-ui/next-ui.adapter.tsx
e-2399-card-kanban-pophover-problemes-dalignement-en-bas-de-la
=> QA : kanban card

shared/features/side-panels/side-panel-header/side-panel-header.tsx
=> QA : sidepanel header

app/manage-projects/[projectSlug]/_sections/activity-section/activity-section.tsx, app/manage-projects/[projectSlug]/features/contributors-table/_components/filter-columns/filter-columns.hooks.tsx, app/manage-projects/[projectSlug]/features/contributors-table/_features/contributors-bulk-sidepanel/contributors-bulk-sidepanel.tsx, design-system/atoms/button/button.types.ts, design-system/atoms/button/variants/button-group.tsx, shared/hooks/contributions/use-contribution-actions.tsx, shared/hooks/rewards/use-can-reward.ts, shared/panels/contribution-sidepanel/_features/footer/footer.tsx, shared/translation/translations/common/common.en.json
e-2329-probleme-pour-recompenser-abdel
=> Bug : no budget && E-2328

shared/panels/project-update-sidepanel/project-update-sidepanel.tsx
e-2410-probleme-de-suppression-davatar-lors-de-ledition-dun-projet
=> Bug : update project

design-system/molecules/modal/adapters/next-ui/next-ui.variants.ts, shared/features/navigation/primary-navigation-mobile/primary-navigation-mobile.tsx, shared/features/notifications/_components/notifications-content/notifications-content.tsx, shared/features/notifications/notifications-modal.tsx, shared/features/notifications/notifications-popover.tsx
e-2411-cant-scroll-in-notifications-on-mobile
=> Bug : notifications mobile

app/data/deep-dive/_features/projects-table/_components/filter-columns/filter-columns.hooks.tsx, app/data/deep-dive/_features/projects-table/_components/filter-columns/filter-columns.types.ts, app/financials/[sponsorId]/_features/programs-table/programs-table.tsx, app/financials/_features/sponsors-table/sponsors-table.tsx, app/manage-projects/features/projects-table/components/filter-columns/filter-columns.hooks.tsx, app/manage-projects/features/projects-table/components/filter-columns/filter-columns.types.ts, app/my-dashboard/_features/rewards-table/_components/filter-columns/filter-columns.hooks.tsx, app/programs/[programId]/_features/projects-table/projects-table.tsx, app/programs/_features/programs-table/programs-table.tsx
b-2768-review-all-table-columns-types
=> Tables types

app/manage-projects/[projectSlug]/_sections/financial-section/components/financial-column-chart/financial-column-chart.hooks.tsx, app/my-dashboard/_sections/financial-section/_components/financial-column-chart/financial-column-chart.en.json, app/my-dashboard/_sections/financial-section/_components/financial-column-chart/financial-column-chart.hooks.tsx, app/my-dashboard/_sections/financial-section/_components/financial-column-chart/financial-column-chart.tsx
b-2711-create-financial-budget-chart-and-add-new-domaine
=> Financial budget chart

app/financials/[sponsorId]/_sections/financial-section/components/transactions-sidepanel/transactions/components/header/header.tsx, app/manage-projects/[projectSlug]/_sections/financial-section/components/transactions-sidepanel/transactions/components/header/header.tsx, app/manage-projects/[projectSlug]/features/contributors-table/contributors-table.tsx, app/programs/[programId]/_features/transactions-sidepanel/transactions/components/header/header.tsx, shared/features/filters/_components/filter-button/filter-button.tsx, shared/features/filters/period-filter/period-filter.tsx, shared/features/filters/period-filter/period-filter.types.ts
e-2424-mettre-le-badge-en-color-brand-when-active-pour-calendar-et
=> Improvment : filter in color && E-2431

shared/features/transactions/_translations/transactions.translate.ts, shared/features/transactions/transactions-accordion/transactions-accordion.tsx, shared/features/transactions/transactions-accordion/transactions-accordion.types.ts, shared/features/transactions/transactions-empty-state/transactions-empty-state.en.json, shared/features/transactions/transactions-empty-state/transactions-empty-state.tsx, shared/features/transactions/transactions-filters/transactions-filters.tsx
refacto/transactions-accordion
=> Refacto : transaction accordion

app/programs/[programId]/financial/_features/budget-available-cards/budget-available-cards.tsx, app/programs/[programId]/financial/_features/budget-available-cards/budget-available.en.json, app/programs/[programId]/financial/_features/transactions/_components/transactions-wrapper/transactions-wrapper.tsx, app/programs/[programId]/financial/_features/transactions/_components/transactions-wrapper/transactions-wrapper.types.ts, app/programs/[programId]/financial/_features/transactions/_translations/transactions.en.json, app/programs/[programId]/financial/_features/transactions/context/transactions.context.tsx, app/programs/[programId]/financial/_features/transactions/context/transactions.context.types.ts, app/programs/[programId]/financial/_features/transactions/transactions.tsx, app/programs/[programId]/financial/page.tsx, app/programs/_translations/programs.translate.ts, design-system/atoms/date-range-picker/adapters/next-ui/next-ui.adapter.tsx, shared/features/transactions/transactions-accordion/transactions-accordion.tsx, shared/features/transactions/transactions-filters/transactions-filters.tsx, shared/panels/contribution-sidepanel/_features/footer/footer.hooks.tsx
e-2484-build-transaction-container-instead-of-transaction-panel
=> Program: transactions

shared/panels/_translations/panels.translate.ts, shared/panels/export-csv-sidepanel/_translations/export-csv-sidepanel.en.json, shared/panels/export-csv-sidepanel/export-csv-sidepanel.hooks.ts, shared/panels/export-csv-sidepanel/export-csv-sidepanel.tsx, shared/panels/export-csv-sidepanel/export-csv-sidepanel.types.ts
=> Refacto export csv panel

app/explore/_components/section/section.tsx, app/explore/_components/section/section.types.ts, app/explore/_features/browse-projects-filters/browse-projects-filters.context.tsx, app/explore/_features/browse-projects-filters/browse-projects-filters.tsx, app/explore/_features/browse-projects-filters/browse-projects-filters.types.ts, app/explore/_features/browse-projects/browse-projects.tsx, app/explore/_features/contributor-leaderboard/contributor-leaderboard.tsx, app/explore/_features/project-leaderboard/project-leaderboard.tsx, app/explore/_features/trending-projects/trending-projects.tsx, app/explore/_translations/explore.translate.ts, app/explore/page.tsx, design-system/molecules/cards/card-project-marketplace/adapters/default/default.adapter.tsx, shared/constants/project-tags.ts, shared/translation/components/translate/translate.types.ts, shared/translation/en.ts, shared/translation/translations/common/common.en.json, shared/translation/translations/projects/project-tags.en.json
- Added a new component `BrowseProjects` to display projects categorized by various tabs.
- Integrated `BrowseProjects` into the `ExplorePage` layout.
- Updated the `TrendingProjects` component to ensure consistent grid layout across devices.
- Enhanced translations to include titles and descriptions for the new browsing feature.
=> Implement BrowseProjects feature in ExplorePage

app/data/contributors/_components/filter-columns/filter-columns.hooks.tsx, app/manage-projects/[projectSlug]/contributors/_features/contributors-table/_components/filter-columns/filter-columns.hooks.tsx, app/manage-projects/[projectSlug]/contributors/_features/contributors-table/contributors-table.context.tsx, core/domain/bi/bi-contract.types.ts, core/domain/bi/models/bi-contributor-list-item-model.ts, core/domain/bi/models/bi-contributor-model.ts, core/infrastructure/marketplace-api-client-adapter/adapters/bi-client-adapter.ts, shared/features/contributors/contributor-profile-checkbox/contributor-profile-checkbox.types.ts, shared/panels/_flows/reward-flow/modals/manage-rewards-modal/_components/filter-columns/filter-columns.hooks.tsx, shared/panels/contributor-sidepanel/_components/public-repo/public-repo.tsx, shared/panels/contributor-sidepanel/_components/public-repo/public-repo.types.ts, shared/panels/contributor-sidepanel/contributor-sidepanel.tsx
- Updated various components and hooks to replace BiContributorInterface with BiContributorListItemInterface for better data handling.
- Introduced BiContributorListItem model to encapsulate contributor data.
- Adjusted context and hooks in contributors table and filter columns to align with the new model.
- Modified API client adapter to return instances of BiContributorListItem.
- Updated types and props across multiple files to ensure consistency with the new contributor model.
This change enhances the structure and clarity of contributor data management throughout the application.
=> Refactor contributor model to use BiContributorListItemInterface

shared/features/side-panels/side-panel-footer/side-panel-footer.tsx, shared/features/side-panels/side-panel-header/side-panel-header.tsx, shared/features/side-panels/side-panel/side-panel.tsx
- Updated SidePanel to use a transparent background and adjusted border styles for tablet view.
- Enhanced SidePanelFooter with a solid top border for better separation.
- Modified SidePanelHeader to include a solid bottom border for improved visual structure.
=> Refactor SidePanel components to improve styling and layout

app/projects/[projectSlug]/layout.tsx, app/projects/[projectSlug]/overview/_features/common-block/common-block.tsx, app/projects/[projectSlug]/overview/_features/common-block/common-block.types.ts, app/projects/[projectSlug]/overview/_features/description/description.tsx, app/projects/[projectSlug]/overview/_features/description/description.types.ts, app/projects/[projectSlug]/overview/_features/stats/stats.tsx, app/projects/[projectSlug]/overview/_features/stats/stats.types.ts, app/projects/[projectSlug]/overview/page.tsx, app/projects/_translations/project-details.en.json, design-system/molecules/accordion/adapters/next-ui/next-ui.adapter.tsx, next.config.mjs
- Added Stats and Description components to the Project Overview page for better project insights.
- Updated layout styles in the Navigation and Paper components for improved responsiveness.
- Introduced new translation keys for project overview statistics and description.
=> Enhance Project Overview with Stats and Description Components

app/projects/[projectSlug]/contributors/_components/contributors-table/contributors-table.tsx, app/projects/[projectSlug]/contributors/_components/contributors-table/filter-columns/filter-columns/filter-columns.hooks.tsx, app/projects/[projectSlug]/contributors/_components/contributors-table/filter-columns/filter-columns/filter-columns.tsx, app/projects/[projectSlug]/contributors/_components/contributors-table/filter-columns/filter-columns/filter-columns.types.ts, app/projects/[projectSlug]/contributors/page.tsx, app/projects/[projectSlug]/issues/page.tsx, app/projects/[projectSlug]/layout.tsx, app/projects/[projectSlug]/overview/_features/stats/stats.tsx, app/projects/[projectSlug]/rewards/_components/rewards-table/filter-columns/filter-columns.hooks.tsx, app/projects/[projectSlug]/rewards/_components/rewards-table/filter-columns/filter-columns.tsx, app/projects/[projectSlug]/rewards/_components/rewards-table/filter-columns/filter-columns.types.ts, app/projects/[projectSlug]/rewards/_components/rewards-table/rewards-table.tsx, app/projects/[projectSlug]/rewards/page.tsx, app/projects/_translations/project-details.en.json, core/application/react-query-adapter/project/client/index.ts, core/domain/github/models/github-label-model.ts, core/domain/project/models/project-model-v2.ts, core/domain/project/project-contract.types.ts, core/infrastructure/marketplace-api-client-adapter/adapters/project-client-adapter.ts, design-system/atoms/badge/adapters/default/default.adapter.tsx, design-system/atoms/badge/badge.types.ts, shared/features/projects/metric/metric.tsx, shared/features/projects/metric/metric.types.ts
…translations  - Added ContributorsTable component to the Project Contributors page for better display of contributor data. - Updated layout.tsx to improve styling and structure of the project overview section. - Introduced new translation keys for contributors in project-details.en.json. - Exported new query hook for fetching project contributors in the project client adapter. - Updated project contract types to include query parameters for contributors. - Enhanced Metric component to accept customizable icon sizes.  These changes improve the user experience by providing clearer contributor information and enhancing the overall layout.
=> Contributors + Rewards + Open Issues
